package demo.online_shop;

import org.hibernate.validator.constraints.NotBlank;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Client implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "CLIENT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "CLIENT_ID_SEQ", name = "CLIENT_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Name")
   @NotBlank
   private java.lang.String name;

   @org.kie.api.definition.type.Label(value = "Country")
   @NotBlank
   private java.lang.String country;

   @org.kie.api.definition.type.Label(value = "Address")
   @NotBlank
   private java.lang.String address;

   public Client()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public Client(java.lang.Long id, java.lang.String name,
         java.lang.String country, java.lang.String address)
   {
      this.id = id;
      this.name = name;
      this.country = country;
      this.address = address;
   }

}