package demo.online_shop;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class OrderLine implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "ORDERLINE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "ORDERLINE_ID_SEQ", name = "ORDERLINE_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Product")
   @NotBlank
   private java.lang.String product;

   @org.kie.api.definition.type.Label(value = "Amount")
   @Min( 1 )
   private java.lang.Integer amount;

   @org.kie.api.definition.type.Label(value = "Price")
   @NotNull
   private java.lang.Double price;

   @org.kie.api.definition.type.Label(value = "Total")
   @NotNull
   private java.lang.Double total;

   public OrderLine()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getProduct()
   {
      return this.product;
   }

   public void setProduct(java.lang.String product)
   {
      this.product = product;
   }

   public java.lang.Integer getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Integer amount)
   {
      this.amount = amount;
   }

   public java.lang.Double getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Double price)
   {
      this.price = price;
   }

   public java.lang.Double getTotal()
   {
      return this.total;
   }

   public void setTotal(java.lang.Double total)
   {
      this.total = total;
   }

   public OrderLine(java.lang.Long id, java.lang.String product,
         java.lang.Integer amount, java.lang.Double price,
         java.lang.Double total)
   {
      this.id = id;
      this.product = product;
      this.amount = amount;
      this.price = price;
      this.total = total;
   }

}