package demo.online_shop;

import javax.validation.Valid;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;

import org.hibernate.validator.constraints.NotBlank;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Order implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "ORDER_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "ORDER_ID_SEQ", name = "ORDER_ID_GENERATOR")
   private java.lang.Long id;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "Client")
   @Valid
   private demo.online_shop.Client client;

   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "Lines")
   private java.util.List<demo.online_shop.OrderLine> lines;

   @org.kie.api.definition.type.Label(value = "Total")
   @Min( 50 )
   @Max( 500000 )
   private java.lang.Double total;

   @org.kie.api.definition.type.Label(value = "Status")
   @NotBlank
   private java.lang.String status;

   @org.kie.api.definition.type.Label(value = "Comments")
   private java.lang.String comments;

   public Order()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public demo.online_shop.Client getClient()
   {
      return this.client;
   }

   public void setClient(demo.online_shop.Client client)
   {
      this.client = client;
   }

   public java.util.List<demo.online_shop.OrderLine> getLines()
   {
      return this.lines;
   }

   public void setLines(java.util.List<demo.online_shop.OrderLine> lines)
   {
      this.lines = lines;
   }

   public java.lang.Double getTotal()
   {
      return this.total;
   }

   public void setTotal(java.lang.Double total)
   {
      this.total = total;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String getComments()
   {
      return this.comments;
   }

   public void setComments(java.lang.String comments)
   {
      this.comments = comments;
   }

   public Order(java.lang.Long id, demo.online_shop.Client client,
         java.util.List<demo.online_shop.OrderLine> lines,
         java.lang.Double total, java.lang.String status,
         java.lang.String comments)
   {
      this.id = id;
      this.client = client;
      this.lines = lines;
      this.total = total;
      this.status = status;
      this.comments = comments;
   }

}