package com.myteam.lists;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Lists implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> listOfStrings;
	private java.util.List<java.lang.Integer> listOfIntegers;
	private java.util.List<java.math.BigDecimal> listOfBigDecimals;

	private java.util.List<java.math.BigInteger> listOfBigIntegers;

	private java.util.List<java.lang.Boolean> listOfBooleans;

	private java.util.List<java.lang.Byte> listOfBytes;

	private java.util.List<java.lang.Character> listOfCharacters;

	private java.util.List<java.util.Date> listOfDates;

	private java.util.List<java.lang.Double> listOfDoubles;

	private java.util.List<java.lang.Float> listOfFloats;

	private java.util.List<java.time.LocalDate> listOfLocalDate;

	private java.util.List<java.time.LocalDateTime> listOfLocalDateTiime;

	private java.util.List<java.time.LocalTime> listOfLocalTime;

	private java.util.List<java.lang.Long> listOfLong;

	private java.util.List<java.time.OffsetDateTime> listOfOffsetDateTIme;

	private java.util.List<java.lang.Short> listOfShort;
	public Lists() {
	}

	public java.util.List<java.lang.String> getListOfStrings() {
		return this.listOfStrings;
	}

	public void setListOfStrings(java.util.List<java.lang.String> listOfStrings) {
		this.listOfStrings = listOfStrings;
	}

	public java.util.List<java.lang.Integer> getListOfIntegers() {
		return this.listOfIntegers;
	}

	public void setListOfIntegers(
			java.util.List<java.lang.Integer> listOfIntegers) {
		this.listOfIntegers = listOfIntegers;
	}

	public java.util.List<java.math.BigDecimal> getListOfBigDecimals() {
		return this.listOfBigDecimals;
	}

	public void setListOfBigDecimals(
			java.util.List<java.math.BigDecimal> listOfBigDecimals) {
		this.listOfBigDecimals = listOfBigDecimals;
	}

	public java.util.List<java.math.BigInteger> getListOfBigIntegers() {
		return this.listOfBigIntegers;
	}

	public void setListOfBigIntegers(
			java.util.List<java.math.BigInteger> listOfBigIntegers) {
		this.listOfBigIntegers = listOfBigIntegers;
	}

	public java.util.List<java.lang.Boolean> getListOfBooleans() {
		return this.listOfBooleans;
	}

	public void setListOfBooleans(
			java.util.List<java.lang.Boolean> listOfBooleans) {
		this.listOfBooleans = listOfBooleans;
	}

	public java.util.List<java.lang.Byte> getListOfBytes() {
		return this.listOfBytes;
	}

	public void setListOfBytes(java.util.List<java.lang.Byte> listOfBytes) {
		this.listOfBytes = listOfBytes;
	}

	public java.util.List<java.lang.Character> getListOfCharacters() {
		return this.listOfCharacters;
	}

	public void setListOfCharacters(
			java.util.List<java.lang.Character> listOfCharacters) {
		this.listOfCharacters = listOfCharacters;
	}

	public java.util.List<java.util.Date> getListOfDates() {
		return this.listOfDates;
	}

	public void setListOfDates(java.util.List<java.util.Date> listOfDates) {
		this.listOfDates = listOfDates;
	}

	public java.util.List<java.lang.Double> getListOfDoubles() {
		return this.listOfDoubles;
	}

	public void setListOfDoubles(java.util.List<java.lang.Double> listOfDoubles) {
		this.listOfDoubles = listOfDoubles;
	}

	public java.util.List<java.lang.Float> getListOfFloats() {
		return this.listOfFloats;
	}

	public void setListOfFloats(java.util.List<java.lang.Float> listOfFloats) {
		this.listOfFloats = listOfFloats;
	}

	public java.util.List<java.time.LocalDate> getListOfLocalDate() {
		return this.listOfLocalDate;
	}

	public void setListOfLocalDate(
			java.util.List<java.time.LocalDate> listOfLocalDate) {
		this.listOfLocalDate = listOfLocalDate;
	}

	public java.util.List<java.time.LocalDateTime> getListOfLocalDateTiime() {
		return this.listOfLocalDateTiime;
	}

	public void setListOfLocalDateTiime(
			java.util.List<java.time.LocalDateTime> listOfLocalDateTiime) {
		this.listOfLocalDateTiime = listOfLocalDateTiime;
	}

	public java.util.List<java.time.LocalTime> getListOfLocalTime() {
		return this.listOfLocalTime;
	}

	public void setListOfLocalTime(
			java.util.List<java.time.LocalTime> listOfLocalTime) {
		this.listOfLocalTime = listOfLocalTime;
	}

	public java.util.List<java.lang.Long> getListOfLong() {
		return this.listOfLong;
	}

	public void setListOfLong(java.util.List<java.lang.Long> listOfLong) {
		this.listOfLong = listOfLong;
	}

	public java.util.List<java.time.OffsetDateTime> getListOfOffsetDateTIme() {
		return this.listOfOffsetDateTIme;
	}

	public void setListOfOffsetDateTIme(
			java.util.List<java.time.OffsetDateTime> listOfOffsetDateTIme) {
		this.listOfOffsetDateTIme = listOfOffsetDateTIme;
	}

	public java.util.List<java.lang.Short> getListOfShort() {
		return this.listOfShort;
	}

	public void setListOfShort(java.util.List<java.lang.Short> listOfShort) {
		this.listOfShort = listOfShort;
	}

	public Lists(java.util.List<java.lang.String> listOfStrings,
				 java.util.List<java.lang.Integer> listOfIntegers,
				 java.util.List<java.math.BigDecimal> listOfBigDecimals,
				 java.util.List<java.math.BigInteger> listOfBigIntegers,
				 java.util.List<java.lang.Boolean> listOfBooleans,
				 java.util.List<java.lang.Byte> listOfBytes,
				 java.util.List<java.lang.Character> listOfCharacters,
				 java.util.List<java.util.Date> listOfDates,
				 java.util.List<java.lang.Double> listOfDoubles,
				 java.util.List<java.lang.Float> listOfFloats,
				 java.util.List<java.time.LocalDate> listOfLocalDate,
				 java.util.List<java.time.LocalDateTime> listOfLocalDateTiime,
				 java.util.List<java.time.LocalTime> listOfLocalTime,
				 java.util.List<java.lang.Long> listOfLong,
				 java.util.List<java.time.OffsetDateTime> listOfOffsetDateTIme,
				 java.util.List<java.lang.Short> listOfShort) {
		this.listOfStrings = listOfStrings;
		this.listOfIntegers = listOfIntegers;
		this.listOfBigDecimals = listOfBigDecimals;
		this.listOfBigIntegers = listOfBigIntegers;
		this.listOfBooleans = listOfBooleans;
		this.listOfBytes = listOfBytes;
		this.listOfCharacters = listOfCharacters;
		this.listOfDates = listOfDates;
		this.listOfDoubles = listOfDoubles;
		this.listOfFloats = listOfFloats;
		this.listOfLocalDate = listOfLocalDate;
		this.listOfLocalDateTiime = listOfLocalDateTiime;
		this.listOfLocalTime = listOfLocalTime;
		this.listOfLong = listOfLong;
		this.listOfOffsetDateTIme = listOfOffsetDateTIme;
		this.listOfShort = listOfShort;
	}

}