package demo.invoices;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Client implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID")
   @Min( 0 )
   @Max( 15 )
   private Long id;
   @org.kie.api.definition.type.Label(value = "Name")

   @NotNull
   @NotBlank
   private String name;
   @org.kie.api.definition.type.Label(value = "Address")
   private String address;

   public Client()
   {
   }

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   public String getName()
   {
      return this.name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public String getAddress()
   {
      return this.address;
   }

   public void setAddress(String address)
   {
      this.address = address;
   }

   public Client(Long id, String name,
         String address)
   {
      this.id = id;
      this.name = name;
      this.address = address;
   }

}
