package demo.invoices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Client implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID")
   private java.lang.Long id;
   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Address")
   private java.lang.String address;

   public Client()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public Client(java.lang.Long id, java.lang.String name,
         java.lang.String address)
   {
      this.id = id;
      this.name = name;
      this.address = address;
   }

}