package demo.invoices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InvoiceLine implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Product")
   private java.lang.Integer product;
   @org.kie.api.definition.type.Label(value = "Quantity")
   private java.lang.Integer quantity;
   @org.kie.api.definition.type.Label(value = "Price")
   private java.lang.Double price;
   @org.kie.api.definition.type.Label(value = "Total")
   private java.lang.Double total;

   public InvoiceLine()
   {
   }

   public java.lang.Integer getProduct()
   {
      return this.product;
   }

   public void setProduct(java.lang.Integer product)
   {
      this.product = product;
   }

   public java.lang.Integer getQuantity()
   {
      return this.quantity;
   }

   public void setQuantity(java.lang.Integer quantity)
   {
      this.quantity = quantity;
   }

   public java.lang.Double getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Double price)
   {
      this.price = price;
   }

   public java.lang.Double getTotal()
   {
      return this.total;
   }

   public void setTotal(java.lang.Double total)
   {
      this.total = total;
   }

   public InvoiceLine(java.lang.Integer product, java.lang.Integer quantity,
         java.lang.Double price, java.lang.Double total)
   {
      this.product = product;
      this.quantity = quantity;
      this.price = price;
      this.total = total;
   }

}