package demo.invoices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Invoice implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Date")
   private java.util.Date date;
   @org.kie.api.definition.type.Label(value = "Comments")
   private java.lang.String comments;
   @org.kie.api.definition.type.Label(value = "client")
   private demo.invoices.Client client;
   @org.kie.api.definition.type.Label(value = "Lines")
   private java.util.List<demo.invoices.InvoiceLine> lines;
   @org.kie.api.definition.type.Label(value = "Total")
   private java.lang.Double total;

   public Invoice()
   {
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public java.lang.String getComments()
   {
      return this.comments;
   }

   public void setComments(java.lang.String comments)
   {
      this.comments = comments;
   }

   public demo.invoices.Client getClient()
   {
      return this.client;
   }

   public void setClient(demo.invoices.Client client)
   {
      this.client = client;
   }

   public java.util.List<demo.invoices.InvoiceLine> getLines()
   {
      return this.lines;
   }

   public void setLines(java.util.List<demo.invoices.InvoiceLine> lines)
   {
      this.lines = lines;
   }

   public java.lang.Double getTotal()
   {
      return this.total;
   }

   public void setTotal(java.lang.Double total)
   {
      this.total = total;
   }

   public Invoice(java.util.Date date, java.lang.String comments,
         demo.invoices.Client client,
         java.util.List<demo.invoices.InvoiceLine> lines,
         java.lang.Double total)
   {
      this.date = date;
      this.comments = comments;
      this.client = client;
      this.lines = lines;
      this.total = total;
   }

}