package com;

import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Types implements java.io.Serializable {
    static final long serialVersionUID = 1L;

    // Text
    private String aString;
    private char aChar;
    private Character aCharacter;

    // Integers
    private int aInt;
    private Integer aInteger;
    private long aLong;
    private Long aLongObject;
    private short aShort;
    private Short aShortObject;
    private BigInteger aBigInteger;

    // Decimal
    private float aFloat;
    private Float aFloatObject;
    private double aDouble;
    private Double aDoubleObject;
    private BigDecimal bigDecimal;

    // Boolean
    private boolean aBoolean;
    private Boolean aBooleanObject;

    public Types() {
    }

    public String getaString() {
        return aString;
    }

    public void setaString(String aString) {
        this.aString = aString;
    }

    public char getaChar() {
        return aChar;
    }

    public void setaChar(char aChar) {
        this.aChar = aChar;
    }

    public Character getaCharacter() {
        return aCharacter;
    }

    public void setaCharacter(Character aCharacter) {
        this.aCharacter = aCharacter;
    }

    public int getaInt() {
        return aInt;
    }

    public void setaInt(int aInt) {
        this.aInt = aInt;
    }

    public Integer getaInteger() {
        return aInteger;
    }

    public void setaInteger(Integer aInteger) {
        this.aInteger = aInteger;
    }

    public long getaLong() {
        return aLong;
    }

    public void setaLong(long aLong) {
        this.aLong = aLong;
    }

    public Long getaLongObject() {
        return aLongObject;
    }

    public void setaLongObject(Long aLongObject) {
        this.aLongObject = aLongObject;
    }

    public short getaShort() {
        return aShort;
    }

    public void setaShort(short aShort) {
        this.aShort = aShort;
    }

    public Short getaShortObject() {
        return aShortObject;
    }

    public void setaShortObject(Short aShortObject) {
        this.aShortObject = aShortObject;
    }

    public BigInteger getaBigInteger() {
        return aBigInteger;
    }

    public void setaBigInteger(BigInteger aBigInteger) {
        this.aBigInteger = aBigInteger;
    }

    public float getaFloat() {
        return aFloat;
    }

    public void setaFloat(float aFloat) {
        this.aFloat = aFloat;
    }

    public Float getaFloatObject() {
        return aFloatObject;
    }

    public void setaFloatObject(Float aFloatObject) {
        this.aFloatObject = aFloatObject;
    }

    public double getaDouble() {
        return aDouble;
    }

    public void setaDouble(double aDouble) {
        this.aDouble = aDouble;
    }

    public Double getaDoubleObject() {
        return aDoubleObject;
    }

    public void setaDoubleObject(Double aDoubleObject) {
        this.aDoubleObject = aDoubleObject;
    }

    public BigDecimal getBigDecimal() {
        return bigDecimal;
    }

    public void setBigDecimal(BigDecimal bigDecimal) {
        this.bigDecimal = bigDecimal;
    }

    public boolean isaBoolean() {
        return aBoolean;
    }

    public void setaBoolean(boolean aBoolean) {
        this.aBoolean = aBoolean;
    }

    public Boolean getaBooleanObject() {
        return aBooleanObject;
    }

    public void setaBooleanObject(Boolean aBooleanObject) {
        this.aBooleanObject = aBooleanObject;
    }
}