package com.myteam.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String str;
	private char cha;
	private java.lang.Character charac;

	public Test() {
	}

	public java.lang.String getStr() {
		return this.str;
	}

	public void setStr(java.lang.String str) {
		this.str = str;
	}

	public char getCha() {
		return this.cha;
	}

	public void setCha(char cha) {
		this.cha = cha;
	}

	public java.lang.Character getCharac() {
		return this.charac;
	}

	public void setCharac(java.lang.Character charac) {
		this.charac = charac;
	}

	public Test(java.lang.String str, char cha, java.lang.Character charac) {
		this.str = str;
		this.cha = cha;
		this.charac = charac;
	}

}