package demo.human_resources;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Street")
   private java.lang.String street;
   @org.kie.api.definition.type.Label(value = "#")
   private java.lang.Integer num;
   @org.kie.api.definition.type.Label(value = "Postal Code")
   private java.lang.String cp;
   @org.kie.api.definition.type.Label(value = "City")
   private java.lang.String city;
   @org.kie.api.definition.type.Label(value = "Country")
   private java.lang.String country;

   public Address()
   {
   }

   public java.lang.String getStreet()
   {
      return this.street;
   }

   public void setStreet(java.lang.String street)
   {
      this.street = street;
   }

   public java.lang.Integer getNum()
   {
      return this.num;
   }

   public void setNum(java.lang.Integer num)
   {
      this.num = num;
   }

   public java.lang.String getCp()
   {
      return this.cp;
   }

   public void setCp(java.lang.String cp)
   {
      this.cp = cp;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public Address(java.lang.String street, java.lang.Integer num,
         java.lang.String cp, java.lang.String city, java.lang.String country)
   {
      this.street = street;
      this.num = num;
      this.cp = cp;
      this.city = city;
      this.country = country;
   }

}